DROP DATABASE IF EXISTS mafia_july2017_jd2;

CREATE DATABASE mafia_july2017_jd2;

USE mafia_july2017_jd2;

DROP TABLE IF EXISTS locations;

CREATE TABLE addresses (locations_id INT UNSIGNED NOT NULL AUTO_INCREMENT, country VARCHAR(30),
  city VARCHAR(30), street VARCHAR(30), house VARCHAR(30), PRIMARY KEY (locations_id), FOREIGN KEY (locations_id) REFERENCES locations(id));
CREATE TABLE locations (id INT UNSIGNED NOT NULL AUTO_INCREMENT, lat VARCHAR (20) NOT NULL,
  'long' VARCHAR(20) NOT NULL, PRIMARY KEY (id));

